# すでに存在するSSHトンネルを使う
#下記2行があるときはSSHトンネルを使う（DBhostをlocalhostとはしないこと）
#DBhost: 127.0.0.1
#DBport: 9999

# SSH接続を使わない
UseSSH: false

# SSH接続を使う
# 下記の設定は、UseSSH: true のときに有効
#UseSSH: true
SSHhost: ${SSHHOST}
SSHport: ${SSHPORT}
SSHuser: ${SSHUSER}
#SSHpswd: ${SSHPSWD}
SSHprvkey: ${SSHKEY}


# データベース名
#DBname:	${DBNAME}
#
# ログイン名とパスワード
DBuser:	${DBUSER}
DBpswd:	${DBPW}