#! /bin/bash

cd /home/chouette/go/src/SaveConfirmedData
# cd /home/chouette/MyProject/Showroom/SaveConfirmedData

source ./my_script.env

# -------------------------------------
# $ cat ./my_script.env
# export DBNAME=......
# export DBUSER=......
# export DBPSWD=......

# export DBPORT=......

# export SSHHOST=......
# export SSHPORT=......
# export SSHUSER=......

# # export SSHPSWD=......
# export SSHKEY=......
# -------------------------------------

./SaveConfirmedData Both